// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXKnKBv0WzEf1Vpe-UuXSmVORc34smKX8',
    appId: '1:855803369317:web:3fa375981a1d3dabcdb38c',
    messagingSenderId: '855803369317',
    projectId: 'todoparaguay',
    authDomain: 'todoparaguay.firebaseapp.com',
    storageBucket: 'todoparaguay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAivVtzYQS-Jzo17tjP1J6iN4aK8uzv5P0',
    appId: '1:855803369317:android:a614e182b5ff4d21cdb38c',
    messagingSenderId: '855803369317',
    projectId: 'todoparaguay',
    storageBucket: 'todoparaguay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVuzn2HAHIazb7ygD5_BAugMN16-mcKTE',
    appId: '1:855803369317:ios:1096ea71aa55c754cdb38c',
    messagingSenderId: '855803369317',
    projectId: 'todoparaguay',
    storageBucket: 'todoparaguay.appspot.com',
    iosClientId: '855803369317-6j4fsjk0nelj6eptgkt9ffhknr7is55p.apps.googleusercontent.com',
    iosBundleId: 'io.todoparaguay.todoParaguay',
  );
}
